[package]
name = "pinnacle"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[lib]
test = false
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
